/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 14-Mar-2020 1:46:30 PM 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS account CASCADE
;

DROP TABLE IF EXISTS cc_type CASCADE
;

DROP TABLE IF EXISTS client CASCADE
;

DROP TABLE IF EXISTS credit_card CASCADE
;

DROP TABLE IF EXISTS demographic_data CASCADE
;

DROP TABLE IF EXISTS disposition CASCADE
;

DROP TABLE IF EXISTS disp_type CASCADE
;

DROP TABLE IF EXISTS frequency CASCADE
;

DROP TABLE IF EXISTS k_symbol CASCADE
;

DROP TABLE IF EXISTS loan CASCADE
;

DROP TABLE IF EXISTS operation CASCADE
;

DROP TABLE IF EXISTS pernament_order CASCADE
;

DROP TABLE IF EXISTS status CASCADE
;

DROP TABLE IF EXISTS trans_type CASCADE
;

DROP TABLE IF EXISTS transaction CASCADE
;

DROP SEQUENCE IF EXISTS seq_loan
;

/* Create Tables */

CREATE SEQUENCE seq_loan
	INCREMENT 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1;

CREATE TABLE account
(
	account_id integer NOT NULL,
	date date NULL,
	district_id integer NULL,
	frequency varchar(50) NULL
)
;

CREATE TABLE cc_type
(
	type varchar(50) NOT NULL
)
;

CREATE TABLE client
(
	client_id integer NOT NULL,
	birth_number integer NULL,
	district_id integer NULL
)
;

CREATE TABLE credit_card
(
	card_id integer NOT NULL,
	disp_id integer NULL,
	issued date NULL,
	type varchar(50) NULL
)
;

CREATE TABLE demographic_data
(
	dist_code integer NOT NULL,
	dist_name varchar(50) NULL,
	region varchar(50) NULL,
	inhabitants integer NULL,
	muni_inhab_499 integer NULL,
	muni_inhab_500_1999 integer NULL,
	muni_inhab_2000_9999 integer NULL,
	muni_inhab_10000 integer NULL,
	cities integer NULL,
	ratio_urban_inhabitants numeric NULL,
	avg_salary integer NULL,
	unemploymant_rate_95 numeric NULL,
	unemploymant_rate_96 numeric NULL,
	enterpreneurs_per_1000 integer NULL,
	commited_crimes_95 integer NULL,
	commited_crimes_96 integer NULL
)
;

CREATE TABLE disposition
(
	disp_id integer NOT NULL,
	account_id integer NULL,
	client_id integer NULL,
	type varchar(50) NULL
)
;

CREATE TABLE disp_type
(
	type varchar(50) NULL
)
;

CREATE TABLE frequency
(
	frequency varchar(50) NOT NULL
)
;

CREATE TABLE k_symbol
(
	k_symbol varchar(30) NOT NULL
)
;

CREATE TABLE loan
(
	loan_id integer NULL,
	account_id integer NULL,
	status varchar(50) NULL,
	amount numeric NULL,
	date timestamp NULL,
	duration integer NULL,
	payments numeric NULL,
	loan_tk bigint NOT NULL DEFAULT nextval('seq_loan'::regclass),
  	version bigint,
  	date_from timestamp without time zone,
  	date_to timestamp without time zone,
  	last_update timestamp without time zone,
	CONSTRAINT "PK_loan" PRIMARY KEY (loan_tk)
)
;

CREATE TABLE operation
(
	operation varchar(30) NOT NULL
)
;

CREATE TABLE pernament_order
(
	order_id integer NOT NULL,
	account_id integer NULL,
	k_symbol varchar(50) NULL,
	account_to integer NULL,
	amount numeric NULL,
	bank_to varchar(2) NULL
)
;

CREATE TABLE status
(
	status char(1) NOT NULL
)
;

CREATE TABLE trans_type
(
	type varchar(10) NOT NULL
)
;

CREATE TABLE transaction
(
	trans_id integer NOT NULL,
	account_id integer NULL,
	k_symbol varchar(30) NULL,
	operation varchar(30) NULL,
	type varchar(10) NULL,
	account integer NULL,
	amount numeric NULL,
	balance numeric NULL,
	bank varchar(2) NULL,
	date date NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE account ADD CONSTRAINT "PK_account"
	PRIMARY KEY (account_id)
;

CREATE INDEX "IXFK_account_demographic_data" ON account (district_id ASC)
;

CREATE INDEX "IXFK_account_frequency" ON account (frequency ASC)
;

ALTER TABLE cc_type ADD CONSTRAINT "PK_cc_type"
	PRIMARY KEY (type)
;

ALTER TABLE client ADD CONSTRAINT "PK_client"
	PRIMARY KEY (client_id)
;

CREATE INDEX "IXFK_client_demographic_data" ON client (district_id ASC)
;

ALTER TABLE credit_card ADD CONSTRAINT "PK_credit_card"
	PRIMARY KEY (card_id)
;

CREATE INDEX "IXFK_credit_card_cc_type" ON credit_card (type ASC)
;

CREATE INDEX "IXFK_credit_card_disposition" ON credit_card (disp_id ASC)
;

ALTER TABLE demographic_data ADD CONSTRAINT "PK_demographic_data"
	PRIMARY KEY (dist_code)
;

ALTER TABLE disposition ADD CONSTRAINT "PK_disposition"
	PRIMARY KEY (disp_id)
;

CREATE INDEX "IXFK_disposition_account" ON disposition (account_id ASC)
;

CREATE INDEX "IXFK_disposition_client" ON disposition (client_id ASC)
;

CREATE INDEX "IXFK_disposition_type" ON disposition (type ASC)
;

ALTER TABLE disp_type ADD CONSTRAINT "PK_type"
	PRIMARY KEY (type)
;

ALTER TABLE frequency ADD CONSTRAINT "PK_frequency"
	PRIMARY KEY (frequency)
;

ALTER TABLE k_symbol ADD CONSTRAINT "PK_k_symbol"
	PRIMARY KEY (k_symbol)
;


CREATE INDEX "IXFK_loan_account" ON loan (account_id ASC)
;

CREATE INDEX "IXFK_loan_status" ON loan (status ASC)
;

ALTER TABLE operation ADD CONSTRAINT "PK_operation"
	PRIMARY KEY (operation)
;

ALTER TABLE pernament_order ADD CONSTRAINT "PK_pernament_order"
	PRIMARY KEY (order_id)
;

CREATE INDEX "IXFK_pernament_order_account" ON pernament_order (account_id ASC)
;

CREATE INDEX "IXFK_pernament_order_k_symbol" ON pernament_order (k_symbol ASC)
;

ALTER TABLE status ADD CONSTRAINT "PK_status"
	PRIMARY KEY (status)
;

ALTER TABLE trans_type ADD CONSTRAINT "PK_trans_type"
	PRIMARY KEY (type)
;

ALTER TABLE transaction ADD CONSTRAINT "PK_transaction"
	PRIMARY KEY (trans_id)
;

CREATE INDEX "IXFK_transaction_account" ON transaction (account_id ASC)
;

CREATE INDEX "IXFK_transaction_k_symbol" ON transaction (k_symbol ASC)
;

CREATE INDEX "IXFK_transaction_operation" ON transaction (operation ASC)
;

CREATE INDEX "IXFK_transaction_trans_type" ON transaction (type ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE account ADD CONSTRAINT "FK_account_demographic_data"
	FOREIGN KEY (district_id) REFERENCES demographic_data (dist_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE account ADD CONSTRAINT "FK_account_frequency"
	FOREIGN KEY (frequency) REFERENCES frequency (frequency) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE disposition ADD CONSTRAINT "FK_disposition_type"
	FOREIGN KEY (type) REFERENCES disp_type (type) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE client ADD CONSTRAINT "FK_client_demographic_data"
	FOREIGN KEY (district_id) REFERENCES demographic_data (dist_code) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE credit_card ADD CONSTRAINT "FK_credit_card_cc_type"
	FOREIGN KEY (type) REFERENCES cc_type (type) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE credit_card ADD CONSTRAINT "FK_credit_card_disposition"
	FOREIGN KEY (disp_id) REFERENCES disposition (disp_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE disposition ADD CONSTRAINT "FK_disposition_account"
	FOREIGN KEY (account_id) REFERENCES account (account_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE disposition ADD CONSTRAINT "FK_disposition_client"
	FOREIGN KEY (client_id) REFERENCES client (client_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE loan ADD CONSTRAINT "FK_loan_account"
	FOREIGN KEY (account_id) REFERENCES account (account_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE loan ADD CONSTRAINT "FK_loan_status"
	FOREIGN KEY (status) REFERENCES status (status) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE pernament_order ADD CONSTRAINT "FK_pernament_order_account"
	FOREIGN KEY (account_id) REFERENCES account (account_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE pernament_order ADD CONSTRAINT "FK_pernament_order_k_symbol"
	FOREIGN KEY (k_symbol) REFERENCES k_symbol (k_symbol) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE transaction ADD CONSTRAINT "FK_transaction_account"
	FOREIGN KEY (account_id) REFERENCES account (account_id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE transaction ADD CONSTRAINT "FK_transaction_k_symbol"
	FOREIGN KEY (k_symbol) REFERENCES k_symbol (k_symbol) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE transaction ADD CONSTRAINT "FK_transaction_operation"
	FOREIGN KEY (operation) REFERENCES operation (operation) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE transaction ADD CONSTRAINT "FK_transaction_trans_type"
	FOREIGN KEY (type) REFERENCES trans_type (type) ON DELETE No Action ON UPDATE No Action
;
